apiVersion: v1
kind: Secret
metadata:
  name: clusterbulb-secrets
  namespace: clusterbulb-monitor
type: Opaque
stringData:
  ha-token: "YOUR_PLAINTEXT_HA_TOKEN"
  gh-token: "YOUR_PLAINTEXT_GH_TOKEN"
# sops --age=$AGE_PUBLIC --encrypt --encrypted-regex '^(data|stringData)$' --in-place clusterbulb-secrets.yaml
